import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[url('/csm_Seidenader-BubbleX-1155_d6fdcaf537.jpg')] h-screen w-screen bg-cover flex items-center justify-center">
        <div className="flex flex-col grow bg-white max-w-7xl rounded-sm shadow-md px-2">
          <div className="text-3xl font-semibold">We are Körber</div>
          <div>Thank you very much for participating in usability testing!</div>
          <div>Do you want to do the test on this device?</div>
          <div>Or would you like to send the link to a mail address?</div>
          <button>Start the test here</button>
          <button>Send to...</button>
        </div>
      </main>
    </>
  );
}
